import { useState } from "react";
import dynamic from "next/dynamic";
const VoiceToText = dynamic(() => import("../components/VoiceToText"), {
  ssr: false,
});
const FuwaFuwaVisualizerWithLinear = dynamic(
  () => import("@/components/FuwaFuwaVisualizerWithLinear"),
  { ssr: false }
);
import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Home() {
  const [started, setStarted] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Voice Recognition Sample.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!started && (
          <button
            onClick={() => setStarted(true)}
            style={{ fontSize: 24, padding: "1em 2em", marginBottom: 32 }}
          >
            音声認識を開始
          </button>
        )}
        <VoiceToText started={started} />
        <FuwaFuwaVisualizerWithLinear started={started} />
      </main>
    </div>
  );
}
