import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import LinearAudioVisualizer from "@/components/LinearAudioVisualizer";
// import FuwaFuwaVisualizer from "@/components/FuwaFuwaVisualizer";
const FuwaFuwaVisualizer = dynamic(
  () => import("@/components/FuwaFuwaVisualizer"),
  { ssr: false }
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FuwaFuwaVisualizer />
      <div style={{ margin: "32px 0" }} />
      <LinearAudioVisualizer />
    </>
  );
}
